version: '3'
services:
  reverseproxy:
    container_name: reverseproxy
    build: .
    image: nginx
    volumes:
    #- ./nginx.conf:/etc/nginx/conf.d/default.conf
    - /home/dohttps/nginx/config/nginx.conf:/etc/nginx/nginx.conf/:rw
    - /home/dohttps/nginx/config/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw
    - /home/dohttps/nginx/logs:/var/log/nginx/:rw
    - /home/dohttps/nginx/ssl:/ssl/:rw
    ports:
    - "80:80"
    - "443:443"
    networks:
      - intregrated-network

networks:
    intregrated-network:
      external: true