version: '3'
services:
  reverseproxy:
    container_name: reverseproxy
    build: .
    image: nginx
    volumes:
    - /home/Maskawa/Reverse-Proxy/https/nginx/data:/usr/share/nginx/html:rw
    - /home/Maskawa/Reverse-Proxy/https/nginx/config/nginx.conf:/etc/nginx/nginx.conf/:rw
    - /home/Maskawa/Reverse-Proxy/https/nginx/config/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw
    - /home/Maskawa/Reverse-Proxy/https/nginx/logs:/var/log/nginx/:rw
    - /home/Maskawa/Reverse-Proxy/https/nginx/ssl:/ssl/:rw -d nginx
    ports:
    - "80:80"
    - "443:443"
    networks:
      intregrated-network

networks:
    intregrated-network:
      external: true